version: '3.1'

services:
  db:
    image: postgres:13.3-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: survey
  app:
    container_name: survey_app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
